### PR TITLE
Refactor code, make it work for the WAQI integration, get wind speed unit from weather entity

### PR DESCRIPTION
**Pull request by Chreece**
I think I'm done...

### CODE REVIEW

**Review by dnguyen800 — APPROVED** [review]
I couldn't get main_pollutant value to display properly but otherwise the WAQI sensors are displaying in the card. Thank you!

**Comment by Chreece** [comment]
> I couldn't get main_pollutant value to display properly but otherwise the WAQI sensors are displaying in the card. Thank you!

The problem is the missing device classes from WAQI sensor, I added them manually on my setup, I will try to make a pull request and add them to core

**Comment by Chreece** [comment]
[Pull request](https://github.com/home-assistant/core/pull/130342) is made, when this will be merged you will see the dominant pollutant value

**Comment by Chreece** [comment]
Closed the pull request as the values provided by the WAQI sensors are not in μg/m3 but as Air Quality Index. So the card should be updated to give AQI as unit of measurement when WAQI integration is used.
I'll try to change the code and make a PR here

**Pull request merged**
